name: Phazecraft
version: 0.1
author: Phazerous
main: com.phazerous.phazerous.Phazerous
api-version: 1.8
commands:
  bal:
    usage: /<command>
  test:
    usage: /<command>
  spawnentity:
    usage: /<command>
  tools:
    usage: /<command>
